FROM python:3.11-slim

RUN apt-get update && apt-get install -y \
    python3-dev build-essential \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

# dépendances Python
COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

# ton code
COPY . .

CMD ["python", "Entree_Sortie.py"]