FROM php:8.2-cli

RUN apt-get update && apt-get install -y \
    git unzip libpng-dev libonig-dev libxml2-dev libzip-dev \
    && docker-php-ext-install pdo pdo_mysql \
    && rm -rf /var/lib/apt/lists/*

# Composer
COPY --from=composer:2 /usr/bin/composer /usr/bin/composer

WORKDIR /app
COPY . /app

# On copie l'entrypoint
COPY entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh

# On installe les dépendances PHP
RUN composer install --no-interaction --prefer-dist --optimize-autoloader

# On laisse l'entrypoint gérer la suite (key, migrate, seed, serve)
ENTRYPOINT ["/entrypoint.sh"]